version: "3.8"

services:
    # PHP Laravel App
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis
            - rabbitmq
        networks:
            - laravel_network
    # NGINX Server
    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - laravel_network
        volumes:
            - mysql_data:/var/lib/mysql

    # Redis Cache
    redis:
        image: redis:latest
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    # phpMyAdmin for DB Access
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - laravel_network

    # RabbitMQ for Queue
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq_service
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672" # RabbitMQ Messaging Port
            - "15672:15672" # RabbitMQ Management Dashboard
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
